var data = [{"pais":"Argentina","ciudad":"General Belgrano"},
{"pais":"Uruguay","ciudad":"Salto"},
{"pais":"Argentina","ciudad":"General José de San Martín"},
{"pais":"Argentina","ciudad":"Maimará"},
{"pais":"Argentina","ciudad":"Dolavón"},
{"pais":"Argentina","ciudad":"Mar del Plata"},
{"pais":"Chile","ciudad":"Longaví"},
{"pais":"Uruguay","ciudad":"Pan de Azúcar"},
{"pais":"Argentina","ciudad":"Aguilares"},
{"pais":"Chile","ciudad":"Victoria"},
{"pais":"Argentina","ciudad":"General Manuel J. Campos"},
{"pais":"Argentina","ciudad":"El Arañado"},
{"pais":"Argentina","ciudad":"Santiago del Estero"},
{"pais":"Uruguay","ciudad":"Nueva Helvecia"},
{"pais":"Uruguay","ciudad":"Villa del Carmen"},
{"pais":"Argentina","ciudad":"Ingenio La Esperanza"},
{"pais":"Brasil","ciudad":"canasbieiras"},
{"pais":"Argentina","ciudad":"Villa Nueva"},
{"pais":"Argentina","ciudad":"Huanchillas"},
{"pais":"Argentina","ciudad":"Chicoana"},
{"pais":"Chile","ciudad":"Chiguayante"},
{"pais":"Argentina","ciudad":"Termas de Río Hondo"},
{"pais":"Argentina","ciudad":"Añatuya"},
{"pais":"Chile","ciudad":"Paine"},
{"pais":"Argentina","ciudad":"Villaguay"},
{"pais":"Argentina","ciudad":"Quemú Quemú"},
{"pais":"Argentina","ciudad":"Tío Pujio"},
{"pais":"Argentina","ciudad":"Carhué"},
{"pais":"Argentina","ciudad":"Bella Vista"},
{"pais":"Argentina","ciudad":"General Arenales"},
{"pais":"Argentina","ciudad":"Victoria"},
{"pais":"Argentina","ciudad":"Villa Santa Rita"},
{"pais":"Argentina","ciudad":"Costa Sacate"},
{"pais":"Chile","ciudad":"Salamanca"},
{"pais":"Argentina","ciudad":"Jesús María"},
{"pais":"Uruguay","ciudad":"Florencio Sánchez"},
{"pais":"Argentina","ciudad":"Ingeniero Guillermo N. Juárez"},
{"pais":"Argentina","ciudad":"Carcarañá"},
{"pais":"Argentina","ciudad":"Apóstoles"},
{"pais":"Argentina","ciudad":"San Juan"},
{"pais":"Argentina","ciudad":"Esquina"},
{"pais":"Argentina","ciudad":"Patquía"},
{"pais":"Uruguay","ciudad":"Villa del Carmen"},
{"pais":"Chile","ciudad":"El Tabo"},
{"pais":"Argentina","ciudad":"Isla Verde"},
{"pais":"Argentina","ciudad":"Cipolletti"},
{"pais":"Argentina","ciudad":"Crespo"},
{"pais":"Argentina","ciudad":"Chimbas"},
{"pais":"Uruguay","ciudad":"Pan de Azúcar"},
{"pais":"Argentina","ciudad":"Miramar"},
{"pais":"Argentina","ciudad":"Contraalmirante Cordero"},
{"pais":"Argentina","ciudad":"Coté-Lai"},
{"pais":"Argentina","ciudad":"Bell Ville"},
{"pais":"Argentina","ciudad":"El Carmen"},
{"pais":"Argentina","ciudad":"Miramar"},
{"pais":"Argentina","ciudad":"San Roque"},
{"pais":"Argentina","ciudad":"Chorotis"},
{"pais":"Argentina","ciudad":"Nueve de Julio"},
{"pais":"Uruguay","ciudad":"Pando"},
{"pais":"Uruguay","ciudad":"Salto"},
{"pais":"Argentina","ciudad":"Cerro Corá"},
{"pais":"Argentina","ciudad":"Laguna Paiva"},
{"pais":"Argentina","ciudad":"Leleque"},
{"pais":"Argentina","ciudad":"Posadas"},
{"pais":"Argentina","ciudad":"General Lavalle"},
{"pais":"Chile","ciudad":"San Clemente"},
{"pais":"Chile","ciudad":"Teno"},
{"pais":"Argentina","ciudad":"Villa Santa Rosa"},
{"pais":"Argentina","ciudad":"Villa Ángela"},
{"pais":"Uruguay","ciudad":"Castillos"},
{"pais":"Argentina","ciudad":"Bell Ville"},
{"pais":"Argentina","ciudad":"General Enrique Mosconi"},
{"pais":"Uruguay","ciudad":"Ecilda Paullier"},
{"pais":"Argentina","ciudad":"Villa Nueva"},
{"pais":"Argentina","ciudad":"Avellaneda"},
{"pais":"Argentina","ciudad":"San Fernando del Valle de Catamarca"},
{"pais":"Uruguay","ciudad":"Porvenir"},
{"pais":"Argentina","ciudad":"Resistencia"},
{"pais":"Argentina","ciudad":"Loreto"},
{"pais":"Argentina","ciudad":"Goya"},
{"pais":"Argentina","ciudad":"La Cocha"},
{"pais":"Argentina","ciudad":"Londres"},
{"pais":"Argentina","ciudad":"San Carlos de Bariloche"},
{"pais":"Argentina","ciudad":"Aranguren"},
{"pais":"Argentina","ciudad":"Campo Quijano"},
{"pais":"Argentina","ciudad":"Chacabuco"},
{"pais":"Argentina","ciudad":"Las Parejas"},
{"pais":"Argentina","ciudad":"Tres Arroyos"},
{"pais":"Argentina","ciudad":"Palpalá"},
{"pais":"Argentina","ciudad":"Pehuajó"},
{"pais":"Uruguay","ciudad":"Salto"},
{"pais":"Argentina","ciudad":"Leleque"},
{"pais":"Argentina","ciudad":"Morteros"},
{"pais":"Argentina","ciudad":"Resistencia"},
{"pais":"Argentina","ciudad":"San Francisco"},
{"pais":"Argentina","ciudad":"Bandera"},
{"pais":"Paraguay","ciudad":"Ciudad del este"},
{"pais":"Argentina","ciudad":"Gualeguaychú"},
{"pais":"Argentina","ciudad":"Ushuaia"},
{"pais":"Argentina","ciudad":"Quilino"},
{"pais":"Argentina","ciudad":"San Justo"},
{"pais":"Uruguay","ciudad":"Tarariras"},
{"pais":"Bolivia","ciudad":"La paz"}];

var mapas = [{'pais':'Argentina','src':"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26093741.39301018!2d-81.59136599955302!3d-37.027180338004044!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bccaf5f5fdc667%3A0x3d2f77992af00fa8!2sArgentina!5e0!3m2!1ses!2sar!4v1571410494841!5m2!1ses!2sar"},
{'pais':'Uruguay','src':"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3442057.5577281485!2d-58.02765872688484!3d-32.595939645751734!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9575073afb5fde09%3A0x4a5596616016524a!2sUruguay!5e0!3m2!1ses!2sar!4v1571411548318!5m2!1ses!2sar"},
{'pais':'Bolivia','src':"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7845677.895790478!2d-68.04354043493679!3d-16.225713017352994!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x915edf8977bba295%3A0x1c9ec2bb0115edbf!2sBolivia!5e0!3m2!1ses!2sar!4v1571411674365!5m2!1ses!2sar"}];